export const ADD_STAFFS = 'ADD_STAFFS';
export const STAFF_LOADING = 'STAFF_LOADING';
export const STAFF_FAILED = 'STAFF_FAILED';
export const STAFF_DELETE = 'STAFF_DELETE';

export const ADD_DEPARTMENT = 'ADD_DEPARTMENT';
export const DEPARTMENT_LOADING = 'DEPARTMENT_LOADING';
export const DEPARTMENT_FAILED = 'DEPARTMENT_FAILED';

export const ADD_STAFFSALARY = 'ADD_STAFFSALARY';
export const STAFFSALARY_LOADING = 'STAFFSALARY_LOADING';
export const STAFFSALARY_FAILED = 'STAFFSALARY_FAILED';